# docker-compose.yml
version: "3"

services:
   generator:
      build: ./generator
      environment:
        KAFKA_BROKER_URL: 172.19.0.3:9092
        TRANSACTIONS_TOPIC: queueing.transactions
        TRANSACTIONS_PER_SECOND: 10

   detector:
      build: ./detector
      environment:
        KAFKA_BROKER_URL: 172.19.0.3:9092
        TRANSACTIONS_TOPIC: queueing.transactions
        LEGIT_TOPIC: streaming.transactions.legit
        FRAUD_TOPIC: streaming.transactions.fraud

networks:
  default:
    external:
      name: kafka-network
